# install with `conda env create -f environment.yaml`

name: assessment
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - jupyter
      - sqlalchemy
      - pandas
      - matplotlib
      - seaborn
      - plotly
